### ISSUE TITLE
JDBC statement function getUpdateCount & getMoreResults

### ISSUE THREAD

**Issue by cpyix** [christophd/citrus-db#18]
In unserem **Tibco SQl Direct** versucht TIBCO automatisch getUpdateCount und getMoreResults aufzurufen, die aktuelle Citrus-DB-Treiber Version wirft eine SQLEXception "Not supported JDBC statement function 'getUpdateCount'"  bzw. "Not supported JDBC statement function 'getMoreResults'" .

Ich habe den Treiber angepasst und als Rückgabewert für getUpdateCount -1 und für getMoreResults false eingefügt. Dann funktioniert alles ohne Porbleme.
Wäre noch zu prüfen in welchem Fall dieser Fix Probleme bereiten  könnte.

**Comment by FMAOuroboros** [comment]
Hallo!

Super! Man müsste mal gucken, was das JDBC Interface dazu sagt und wie sich die Werte innerhalb einer Kommunikation mit der Datenbank ermitteln sollen.

**Comment by FMAOuroboros** [comment]
Closed by https://github.com/christophd/citrus-db/pull/19

Thx a lot for your help!
