### ISSUE TITLE
Add support for stored procedures

### ISSUE THREAD

**Issue by FMAOuroboros** [christophd/citrus-db#2]
As a test designer, I want to be able to create, execute and validate stored procedures calls to the database to ensure, that my software is calling the procedures correctly. In addition exceptions should be thrown if the stored procedure does not exist or does not match.

**Comment by FMAOuroboros** [comment]
Here are examples for [oracle stored procedures](https://docs.oracle.com/cd/B28359_01/java.111/b31225/chseven.htm#CACGIFAD).
The procedures are handled via CallableStatement, which we would need to implement.

**Comment by FMAOuroboros** [comment]
First of all, this feature will be implemented in the embedded version of citrus-db and not within the standalone one

**Comment by FMAOuroboros** [comment]
Resolved with f3290c8

**Comment by sharath888** [comment]
With CitrusFrame work, how to execute a procedure?
